[book]
authors = ["seven_bear"]
language = "zh-CN"
src = "src"
title = "WebAssembly 深入教程"
description = "从基础到实践的 WebAssembly 完整教程"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "ayu"
smart-punctuation = true
mathjax-support = true
copy-fonts = true
git-repository-url = "https://github.com/your-username/wasm-book"
edit-url-template = "https://github.com/your-username/wasm-book/edit/main/src/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
